# Generated by Django 5.2.3 on 2025-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Google OAuth2 Client ID', max_length=255, unique=True)),
                ('client_secret', models.CharField(help_text='Google OAuth2 Client Secret', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Google Credentials',
            },
        ),
    ]
