# Generated by Django 4.2.7 on 2025-08-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredential',
            name='redirect_uri',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
